version: '2'
services:
  web:
    image: hello_dev_i
    container_name: hello_dev_c
    build:
      context: .
    command: npm run dev
    environment:
      NAME: Dave
    ports:
     - "3333:3333"
    volumes:
     - .:/usr/src/app
